name: ChatGPT Code Review

on:
  pull_request:
    paths:
      - "*.py"
      - "*.php" # PHPファイルを追加

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          MODEL: gpt-4
          PROMPT: "Please review the following PHP code diff for potential issues."
          IGNORE_PATTERNS: /node_modules,*.md # PHPを除外しない
